### ISSUE TITLE
Implementing the SST kw model

### ISSUE THREAD

**Issue by jethromoses** [argonne-lcf/TensorFlowFoam#11]
Hi, 

In your paper you have implemented the SST kw model as well. I was wondering if it was possible for you to upload the equivalent ML_SA_CG.C file. I was hoping to implement this turbulence model.

**Comment by Romit-Maulik** [comment]
Hi @jethromoses - we implemented KOSST only for the same geometry and inlet velocity (as a proof of principle) - so I haven't added that case to this repo. It would be an interesting exercise for you to extend what we have now to the KOSST model. If you're having trouble or would rather not wait - I can exchange some files with you offline (my email is rmaulik@anl.gov).

**Comment by jethromoses** [comment]
Thanks for the files!
