### ISSUE TITLE
Linking tensorflow to openfoam

### ISSUE THREAD

**Issue by jethromoses** [argonne-lcf/TensorFlowFoam#12]
I have not installed tensorflow in the default location. So, I modified the OF_model/Make/options file to 

EXE_INC = \
    -I$(LIB_SRC)/TurbulenceModels/turbulenceModels/lnInclude \
    -I$(LIB_SRC)/TurbulenceModels/incompressible/lnInclude \
    -I$(LIB_SRC)/transportModels \
    -I$(LIB_SRC)/finiteVolume/lnInclude \
    -I$(LIB_SRC)/meshTools/lnInclude \
    -I/work/SDDO_lab/jethro/software_installations/tf_1_15/include \

LIB_LIBS = \
    -lincompressibleTransportModels \
    -lturbulenceModels \
    -lfiniteVolume \
    -lmeshTools \
    -L/work/SDDO_lab/jethro/software_installations/tf_1_15/lib \
    -lstdc++

It managed to compile it without any error, however, when I try to run simpleFoam_ML in the Testing folder, I get the following error

simpleFoam_ML: symbol lookup error: /home/jethro/OpenFOAM/jethro-5.x/platforms/linux64IccDPInt32Opt/lib/ML_SST_CG.so: undefined symbol: TF_NewBuffer

I am not sure where I am going wrong.

**Comment by Romit-Maulik** [comment]
Have you made sure to add the `-ltensorflow` flag in the `LIB_LIBS` section?

**Comment by Romit-Maulik** [comment]
You should also append the path to the new tensorflow `/lib/` folder to your `LD_LIBRARY_PATH`
```
export LD_LIBRARY_PATH=/work/SDDO_lab/jethro/software_installations/tf_1_15/lib:$LD_LIBRARY_PATH
```

**Comment by jethromoses** [comment]
I added the -ltensorflow flag after the  -L/work/SDDO_lab/jethro/software_installations/tf_1_15/lib flag in the LIB_LIBS section. I also  append the path to the new tensorflow /lib/ . I still get the same error.

**Comment by Romit-Maulik** [comment]
Hi Jethro - can you cd to `$FOAM_USER_LIBBIN` and check the output of `ldd ML_SA_CG.so` (or whatever the name of your so file is). There should be no broken links here.
