### ISSUE TITLE
Pip install requirements error

### ISSUE THREAD

**Issue by rohitvuppala** [argonne-lcf/TensorFlowFoam#13]
I've created a new conda environment on Ubuntu 18.04.5 LTS  and tried to the use the command:

`pip install -r requirements.txt`

I get the following error:
`
ERROR: Could not find a version that satisfies the requirement ipykernel==5.2.1 (from -r requirements.txt (line 18)) (from versions: 4.0.1, 4.0.2, 4.0.3, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.5.0, 4.5.1, 4.5.2, 4.6.0, 4.6.1, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.9.0, 4.10.0, 4.10.1)
ERROR: No matching distribution found for ipykernel==5.2.1 (from -r requirements.txt (line 18))
`
I'm not sure what I'm missing.

`pip --version` gives:
pip 20.1.1 from /locationtoanaconda/anaconda/lib/python3.8/site-packages/pip (python 3.8)

**Comment by Romit-Maulik** [comment]
Hello. Thanks for trying out our package. This may be a python version issue I think. All these codes were tested with Python 3.6.9. Can you try that?

**Comment by rohitvuppala** [comment]
Yes, that seems to fix the issue while installing the requirements.txt. Could you please add this to the instructions?

**Comment by Romit-Maulik** [comment]
Thanks. Added.
