### ISSUE TITLE
Generating Training Data (and OpenFOAM 5)

### ISSUE THREAD

**Issue by rohitvuppala** [argonne-lcf/TensorFlowFoam#15]
I'm trying to generate the training data for the backward step case instead of using data provided. I see that you need wall distance, u,v,w velocities and coordinates for cell centres. I have two brief questions: 
1. How did you write out your wall distances in OpenFOAM5 so that it is readable by "training_data_marker.py"? (For cellcentres I just used the inbuilt func)
2. Could you elaborate on how files need to be setup for the "training_data_maker.py" to create the total array data set for training?

**Comment by Romit-Maulik** [comment]
Hello,

To write out arbitrary quantities like wall distances - you need to make a modification to a standard RANS model and recompile as a separate (more detailed) model. For example in your Spalart-Allmaras model you can add the following
```
if(this->runTime_.outputTime())
{
y_.write();
}
```
Note that the template constructor for the RANS model defines the wall distance with `y_` as follows
```
y_(wallDist::New(this->mesh_).y())
```
You can make temporary variables in the same manner and write them to disk. For example, if you want to write out the magnitude of the strain-rate tensor in real-time you can use
```
volScalarField strain_ = sqrt(2.0)*mag(symm(fvc::grad(this->U_)));
const char* strain_name = "strain";
strain_.rename(strain_name);
strain_.write();
```
Finally, cell-center coordinate information can be obtained by a convenient OpenFOAM postprocessing utility
```
postProcess -latestTime -func writeCellCentres
```

Hope this helps.

**Comment by rohitvuppala** [comment]
@Romit-Maulik thank I found the post processing utility for cell centers but couldn't figure out the wall distance part. Thanks for your detailed explanation really appreciate it!. 

For the second question, I'm assuming you then just rename these openfoam files accordingly for the python script and use it for training?.

**Comment by Romit-Maulik** [comment]
That's correct.

**Comment by rohitvuppala** [comment]
Thank you!
