### ISSUE TITLE
Comparison vs two-eq turbulence models

### ISSUE THREAD

**Issue by JorisCodde** [argonne-lcf/TensorFlowFoam#2]
Hello,

This is more of a question than an issue, really. But it might be of interest to more people. Do you plan om making an extension to two-eq RAS turbulence models? Such as k-Epsilon.

In the abstract of your paper I saw only a reference to 1-eq models.

Seems really cool work in any case though

Joris

**Comment by Romit-Maulik** [comment]
Hi Joris,

Thanks for your interest in our work. We have shown a couple of cases in our paper where we provided emulators for KOSST and RNG-KE (Section 3.4). We have not uploaded these models here but they should be easy to implement. Perhaps we can add those as examples in the future.

This repository serves as an introduction to how you may incorporate an arbitrary DL inference task within OpenFOAM. It doesn't have to be turbulence closure modeling - it may be DL based compression/data assimilation/surrogate modeling or neural network parameterizations for limiters. We are trying to provide a framework that can enable a broad spectrum of research.

**Comment by JorisCodde** [comment]
Hi Romit,

Thank you for your reply. Using this as a framework definitely gives some interesting possibilities.

I will let you know in case we're building on this.

Joris
