### ISSUE TITLE
Step height values

### ISSUE THREAD

**Issue by jethromoses** [argonne-lcf/TensorFlowFoam#8]
In training_data_maker.py, cases 5 and 6 both have step heights of 1.75. Shouldn't they be different?

**Comment by Romit-Maulik** [comment]
Hi @jethromoses - good catch! I've updated the typo (case 6 should be 1.25 h) and reran the training and inference. The skin friction on the testing case is seen to be a bit more accurate after this fix. Here's the old skin friction
![CF_DG2](https://user-images.githubusercontent.com/12647892/93126763-6a760900-f692-11ea-873b-9920080f254a.png)
and here's the new one
![CF_DG2_New](https://user-images.githubusercontent.com/12647892/93126815-78c42500-f692-11ea-9fe3-33749d893fc7.png)
The errors are slightly reduced downstream of the reattachment point.

**Comment by jethromoses** [comment]
Awesome, thank!

**Comment by jethromoses** [comment]
In the skin friction plots shown above, the ML and SA models match pretty well. However, in your paper (Fig 16), the same plots are significantly more different, ever before you corrected the typo in case 6. 

The reason I am asking, is because, the skin friction results I have gotten do not match very well, like in Fig 16 in your paper. I was wondering if there were any changes you have made in your code that would improve the skin friction prediction for the ML case?

**Comment by Romit-Maulik** [comment]
Hi Jethro - the paper online has not been updated - but we changed our ML_Model activation functions from ReLU to Tanh. That meant that the predicted eddy viscosity was much smoother. That led to the improved skin friction predictions,
