### ISSUE TITLE
Step height during testing

### ISSUE THREAD

**Issue by jethromoses** [argonne-lcf/TensorFlowFoam#9]
In the Testing folder, constant/turbulenceProperties has hh_ set to 1.9. However, in system/blockMeshDict, the step height seems to be 1. Am I missing something?

**Comment by Romit-Maulik** [comment]
Sorry that blockMeshDict is outdated. The mesh height of 1.9h is accurate. These meshes were generated Cubit.

**Comment by jethromoses** [comment]
Thanks!
Also, do we need yWall_1, yWall_2 ... in Data_generation/OF_Data? Doesn't seemed to be used during training the NN

**Comment by Romit-Maulik** [comment]
Yes - that is extra data we didn't end up needing.

**Comment by jethromoses** [comment]
Is it possible for you to upload the updated blockMeshDict that was used to generate the mesh for the 1.9h case?

**Comment by Romit-Maulik** [comment]
We did not use blockMesh for that case - it was generated by Cubit. I can upload a link the *.msh file if that can help - its rather large.

**Comment by jethromoses** [comment]
No, it's fine. Thank you though!
